# ==== 模块信息 ==== #

__version__ = "4.9.10.1"

__author__ = "Qeggs"
__license__ = "MIT"
__copyright__ = "Copyright (c) 2025 Qeggs"
__remarks__ = "Some of the code here is generated by AI."

__github__ = [
    "https://github.com/repeater-bot/repeater-ai-chatbot",
    "https://github.com/repeater-bot/repeater-onebot-v11-client",
    "https://github.com/repeater-bot/repeater-nexus",
    "https://github.com/repeater-bot/repeater-notes-client",
    "https://github.com/qeggs-dev/auto-backup",
    "https://github.com/repeater-bot/repeater-document-library",
    "https://github.com/repeater-bot/repeater-model-info-server",
    "https://github.com/qeggs-dev/static-resources-server",
    "https://github.com/repeater-bot/repeater-static-data",
    "https://github.com/repeater-bot/repeater-render-server",
]